quarkus.devservices.enabled=true

quarkus.native.container-build=true
quarkus.native.container-runtime=docker

quarkus.mailer.from=test@example.com
%prod.quarkus.mailer.host=localhost
%prod.quarkus.mailer.port=1025

quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.image-name=postgres:18-alpine
quarkus.datasource.devservices.port=5432
quarkus.datasource.devservices.db-name=registration
quarkus.datasource.devservices.username=user
quarkus.datasource.devservices.password=password
%prod.quarkus.datasource.username=user
%prod.quarkus.datasource.password=password
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/registration_db

quarkus.hibernate-orm.multitenant=DISCRIMINATOR
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.flyway.active=true
quarkus.flyway.migrate-at-start=true

quarkus.oidc.application-type=web-app
%prod.quarkus.oidc.auth-server-url=https://id.ijug.eu/realms/ijug
quarkus.oidc.client-id=registration
quarkus.oidc.credentials.secret=secret
quarkus.oidc.roles.role-claim-path=resource_access/registration/roles
quarkus.oidc.authentication.pkce-required=true
quarkus.oidc.authentication.redirect-path=/oidc/callback
quarkus.oidc.authentication.restore-path-after-redirect=true
#quarkus.oidc.logout.path=/logout
#quarkus.oidc.logout.post-logout-path=/index.html

quarkus.keycloak.devservices.realm-path=ijug-realm.json
quarkus.keycloak.devservices.port=8081

quarkus.cache.caffeine."events".initial-capacity=10
quarkus.cache.caffeine."events".expire-after-write=5m

# TEST specific configuration

%test.quarkus.mailer.mock=true
