services:
  database:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registration_db

  mailpit:
    image: docker.io/axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
